### ISSUE TITLE
qiita db load_raw requires the input data to be on a writable filesystem?

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#1094]
Just got this, was very surprised. Why does the source path need to be a writable filesystem?

``` bash
(qiita)18:19:36 (qiita@qiita):scripts$ ./qiita db load_raw --fp /sequencing/ucsd/complete_runs/150420_M00436_0038_000000000-ABMKV/Data/Intensities/BaseCalls/Pool_S1_L001_I1_001.fastq.gz --fp_type raw_barcodes --filetype FASTQ --study 10129
Traceback (most recent call last):
  File "./qiita", line 415, in <module>
    qiita()
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "./qiita", line 123, in load_raw
    raw_data = load_raw_data_cmd(fp, fp_type, filetype, study)
  File "/home/qiita/qiita_main/qiita_db/commands.py", line 208, in load_raw_data_cmd
    filepaths=list(zip(filepaths, filepath_types)))
  File "/home/qiita/qiita_main/qiita_db/data.py", line 329, in create
    rd.add_filepaths(filepaths, conn_handler)
  File "/home/qiita/qiita_main/qiita_db/data.py", line 167, in add_filepaths
    raise e
OSError: [Errno 30] Read-only file system: '/sequencing/ucsd/complete_runs/150420_M00436_0038_000000000-ABMKV/Data/Intensities/BaseCalls/Pool_S1_L001_I1_001.fastq.gz'
```

**Comment by wasade** [comment]
On further inspection, I see the issue. It is moving the files instead of copying. I'm leaving this open as the error message should be more informative. Removing bug label though

**Comment by ElDeveloper** [comment]
I actually would like to see a `--copy` flag.

**Comment by antgonza** [comment]
--copy :+1:

**Comment by colinbrislawn** [comment]
I just got the "Read-only file system" error. Is this a related issue or something different?
![screen shot 2016-09-26 at 3 38 32 pm](https://cloud.githubusercontent.com/assets/10355152/18854339/91a3c88c-83ff-11e6-93c0-d2316c55b893.png)

**Comment by colinbrislawn** [comment]
I removed that full Sample Info File and then reposted the full sample info file and prep info file. That worked, but now I got it again when trying to associate per_sample_FASTQ files with that prep.  
![screen shot 2016-09-26 at 3 51 34 pm](https://cloud.githubusercontent.com/assets/10355152/18854612/82993064-8401-11e6-85ad-0d18c1bb12cb.png)

😦

**Comment by antgonza** [comment]
@colinbrislawn could you try again?

**Comment by colinbrislawn** [comment]
This now works for me. Thank you!
(I can remove these comments if it is off topic for this thread.)

**Comment by antgonza** [comment]
Your welcome and thanks for reporting. BTW leave them.

**Comment by antgonza** [comment]
Closing as this is superseded by https://github.com/biocore/qiita/issues/1067
