### ISSUE TITLE
illegal operation on non-sandbox study

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#1164]
I was editing the study description for study 1902 (http://qiita.microbio.me/study/edit/1902), which is private, and I changed the study title and the abstract. When I hit the submit button, I got a 500 error:

```
ERROR:
Illegal operation on non-sandbox study!
TRACE:
Traceback (most recent call last):

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
callback()

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
self._when_complete(method(*self.path_args, **self.path_kwargs),

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 2297, in wrapper
return method(self, *args, **kwargs)

File "/home/qiita/qiita_main/qiita_pet/handlers/study_handlers/edit_handlers.py", line 273, in post
'environmental_packages']

File "/home/qiita/qiita_main/qiita_db/study.py", line 703, in environmental_packages
self._lock_non_sandbox(conn_handler)

File "/home/qiita/qiita_main/qiita_db/study.py", line 158, in _lock_non_sandbox
raise QiitaDBStatusError("Illegal operation on non-sandbox study!")

QiitaDBStatusError: Illegal operation on non-sandbox study!
```
When I go back to the edit page, I see that the title and abstract were updated successfully. It looks like the edit page thinks I'm trying to change the environmental packages, even though I'm not (and the option to change the environmental packages was not offered on the edit page, since the study is private).

**Comment by josenavas** [comment]
Thanks @adamrp I've added added to the Alpha 0.2 milestone and assigned as a high priority issue, as I can see this a bug that can disturb a lot of users. Thanks for the detailed error report!
