### ISSUE TITLE
qiita_db if database doesn't exist should fail nicely 

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#134]
Currently fails with:
qiita_db.exceptions.QiitaDBExecutionError: 
Error running SQL query: select filepath_type, filepath_type_id from qiita.filepath_type
Error: relation "qiita.filepath_type" does not exist
LINE 1: select filepath_type, filepath_type_id from qiita.filepath_t...

**Comment by antgonza** [comment]
I think we can do better than this:
```
Traceback (most recent call last):
  File "/Users/antoniog/svn_programs/qiita/scripts/qiita", line 20, in <module>
    from qiita_db.commands import (load_sample_template_from_cmd,
  File "/Users/antoniog/svn_programs/qiita/qiita_db/commands.py", line 23, in <module>
    from .metadata_template import (SampleTemplate, PrepTemplate,
  File "/Users/antoniog/svn_programs/qiita/qiita_db/metadata_template.py", line 1149, in <module>
    class SampleTemplate(MetadataTemplate):
  File "/Users/antoniog/svn_programs/qiita/qiita_db/metadata_template.py", line 1165, in SampleTemplate
    'required_sample_info_status_id': get_required_sample_info_status()}
  File "/Users/antoniog/svn_programs/qiita/qiita_db/util.py", line 217, in get_required_sample_info_status
    con = SQLConnectionHandler()
  File "/Users/antoniog/svn_programs/qiita/qiita_db/sql_connection.py", line 120, in __init__
    self._open_connection()
  File "/Users/antoniog/svn_programs/qiita/qiita_db/sql_connection.py", line 155, in _open_connection
    raise RuntimeError("Cannot connect to database: %s" % str(e))
RuntimeError: Cannot connect to database: FATAL:  the database system is shutting down
```

**Comment by antgonza** [comment]
This is much nicer:
```
RuntimeError: An OperationalError with the following message occured

	could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

This is likely because postgres isn't running. Check that postgres is correctly installed and is running. For more information, review `INSTALL.md` in the Qiita installation base directory.
```

Closing
