### ISSUE TITLE
EBI submission will fail silently if there are non-ascii characters in the templates

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#1398]
It will raise the following error, but it won't be visible through the graphical user interface, the insdc status will still appear as 'submitting'.

```python
Traceback (most recent call last):
  File "/home/qiita/qiita_main/scripts/qiita", line 486, in <module>
    qiita()
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/qiita/qiita_main/scripts/qiita", line 362, in submit
    _submit_EBI(preprocessed_data_id, action, send, fastq_dir)
  File "/home/qiita/qiita_main/qiita_ware/commands.py", line 146, in submit_EBI
    submission_fp, action)
  File "/home/qiita/qiita_main/qiita_ware/ebi.py", line 784, in write_all_xml_files
    self.write_experiment_xml(experiment_fp)
  File "/home/qiita/qiita_main/qiita_ware/ebi.py", line 725, in write_experiment_xml
    'experiment_xml_fp', fp)
  File "/home/qiita/qiita_main/qiita_ware/ebi.py", line 677, in _write_xml_file
    xml = minidom.parseString(ET.tostring(xml_element))
  File "/opt/python-2.7.3/lib/python2.7/xml/etree/ElementTree.py", line 1127, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/opt/python-2.7.3/lib/python2.7/xml/etree/ElementTree.py", line 821, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/opt/python-2.7.3/lib/python2.7/xml/etree/ElementTree.py", line 940, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/opt/python-2.7.3/lib/python2.7/xml/etree/ElementTree.py", line 940, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/opt/python-2.7.3/lib/python2.7/xml/etree/ElementTree.py", line 940, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/opt/python-2.7.3/lib/python2.7/xml/etree/ElementTree.py", line 940, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/opt/python-2.7.3/lib/python2.7/xml/etree/ElementTree.py", line 938, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/opt/python-2.7.3/lib/python2.7/xml/etree/ElementTree.py", line 1074, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 578: ordinal not in range(128)
```

**Comment by antgonza** [comment]
Fixed in #1451
