### ISSUE TITLE
Submit to EBI GUI is not working

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1619]
This is the error that we are receiving:
```
ERROR:
'Artifact' object has no attribute 'prep_template'
TRACE:
Traceback (most recent call last):

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
callback()

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
self._when_complete(method(*self.path_args, **self.path_kwargs),

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 2297, in wrapper
return method(self, *args, **kwargs)

File "/home/qiita/qiita_main/qiita_pet/handlers/study_handlers/ebi_handlers.py", line 96, in get
self.display_template(preprocessed_data_id, "", "")

File "/home/qiita/qiita_main/qiita_core/util.py", line 94, in wrapper
return func(*args, **kwargs)

File "/home/qiita/qiita_main/qiita_pet/handlers/study_handlers/ebi_handlers.py", line 42, in display_template
prep_template = PrepTemplate(preprocessed_data.prep_template)

AttributeError: 'Artifact' object has no attribute 'prep_template'```

**Comment by antgonza** [comment]
This was already solved.
