### ISSUE TITLE
EBI submission is not working

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1628]
This is the error that we receive:
```
Traceback (most recent call last):
  File "/home/qiita/qiita_main/scripts/qiita", line 431, in <module>
    qiita()
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/qiita/qiita_main/scripts/qiita", line 305, in submit
    _submit_EBI(preprocessed_data_id, action, send)
  File "/home/qiita/qiita_main/qiita_ware/commands.py", line 135, in submit_EBI
    ebi_submission.preprocessed_data.ebi_run_accessions = run_acc
AttributeError: 'EBISubmission' object has no attribute 'preprocessed_data'
```

@antgonza do you have a chance to take a look? I may be able to take a look tomorrow.

**Comment by antgonza** [comment]
I have a fix ready, it's simple but I wanted to put together the full testing framework. How urgent is this? If not that urgent I can potentially have the new testing ready by Monday evening.
