### ISSUE TITLE
Better error when split libraries doesn't yield any sequences. 

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1690]
The current error is:
```
Status: Job 42cadf02-5ad8-4104-a211-4d4be7c6b866: failed - Error executing Split libraries:
['Traceback (most recent call last):\n', ' File "/home/qiita/qiita_main/qiita_plugins/target_gene/tgp/plugin.py", line 56, in execute_job\n output_dir)\n', ' File "/home/qiita/qiita_main/qiita_plugins/target_gene/tgp/split_libraries/split_libraries.py", line 285, in split_libraries\n generate_demux_file(output_dir)\n', ' File "/home/qiita/qiita_main/qiita_plugins/target_gene/tgp/split_libraries/util.py", line 140, in generate_demux_file\n to_hdf5(fastq_fp, f)\n', ' File "/home/qiita/qiita_main/qiita_ware/demux.py", line 355, in to_hdf5\n sample_stats, full_stats = _summarize_lengths(_per_sample_lengths(fp))\n', ' File "/home/qiita/qiita_main/qiita_ware/demux.py", line 243, in _summarize_lengths\n full_stats = stat(n=all_lengths.size, max=all_lengths.max(),\n', ' File "/opt/numpy/1.7.2/lib/python2.7/site-packages/numpy/core/_methods.py", line 10, in _amax\n out=out, keepdims=keepdims)\n', 'ValueError: zero-size array to reduction operation maximum which has no identity\n']
```

**Comment by josenavas** [comment]
Just to build a bit of intuition on how to fix this:  the error is raised from the generation of the demux file. Before doing such call, we should check if the output FASTQ files is empty or not.
