### ISSUE TITLE
reset password errors are not shown in GUI

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1802]
When users try to reset their password and the password is not valid the error is not shown to the user and only a 500 error is shown.

**Comment by josenavas** [comment]
Any error in the logs?

**Comment by antgonza** [comment]
```
ERROR:
Bad password given!
TRACE:
Traceback (most recent call last):

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
callback()

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
self._when_complete(method(*self.path_args, **self.path_kwargs),

File "/home/qiita/qiita_main/qiita_core/util.py", line 103, in wrapper
return func(*args, **kwargs)

File "/home/qiita/qiita_main/qiita_pet/handlers/user_handlers.py", line 140, in post
changed = user.change_forgot_password(code, newpass)

File "/home/qiita/qiita_main/qiita_db/user.py", line 575, in change_forgot_password
self._change_pass(newpass)

File "/home/qiita/qiita_main/qiita_db/user.py", line 582, in _change_pass
raise IncorrectPasswordError("Bad password given!")

IncorrectPasswordError: Bad password given!
```

**Comment by josenavas** [comment]
Thanks @antgonza 

I think this shows that there are 2 things missing:
 1. A try/except in the handler
 2. A JS call to check the format of the password, as it is done in the signup page.
