### ISSUE TITLE
Fix setup.py and update INSTALL.md installation documentation accordingly

### ISSUE THREAD

**Issue by HannesHolste** [biocore/qiita#1847]
The [ current one ](https://github.com/biocore/qiita/commit/378be825d8b4d147180774606a589f9f2051909f) is outdated, causing users to encounter various errors when trying to follow the tutorial.

I will update these instructions and add notes on the use of conda/miniconda and Mac OSX installation.

Can an admin assign me to this in GitHub?

**Comment by antgonza** [comment]
Great, thanks!

**Comment by HannesHolste** [comment]
Almost finished.

Currently wrangling with this issue: the package 'biom' uses
`from future.utils import string_types`
which apparently has been removed after future v.0.13.1 (see: https://github.com/biocore/scikit-bio/issues/691)

However, simply downgrading the local package version of future as suggested [here](https://github.com/biocore/scikit-bio/issues/691#issuecomment-57902757) did not work; it raises the same error.

`> qiita pet webserver
Traceback (most recent call last):
  File "/Users/hannes/miniconda2/envs/qiita/bin/qiita", line 24, in <module>
    import qiita_db as qdb
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/qiita_db/__init__.py", line 13, in <module>
    import analysis
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/qiita_db/analysis.py", line 25, in <module>
    from biom import load_table
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/biom/table.py", line 188, in <module>
    from future.utils import string_types
ImportError: cannot import name string_types
(qiita)`


@ElDeveloper any insight into this?

**Comment by antgonza** [comment]
Strange, my guess is that you have something leftover because in my installation I have:
```bash
(qiita)14:24:15 qiita@validate-prep-fixes$ python -c 'import future; print future.__version__'
0.15.2
(qiita)14:24:41 qiita@validate-prep-fixes$ python -c 'import biom; print biom.__version__'
2.1.5
```

**Comment by ElDeveloper** [comment]
The development version of biom-format is dependent on future >= 0.15, see this [patch](https://github.com/biocore/biom-format/commit/4da9ffdae6ea4f2c9e335ba81f5cfcbd95e00ea2). I think it should be safe to upgrade to 0.15, unless this conflicts with scikit-bio 0.2.3 (which doesn't seem to be the case https://github.com/biocore/scikit-bio/blob/0.2.3/setup.py).

**Comment by antgonza** [comment]
Right, so use the dev version of biom-format and a newer future.

**Comment by HannesHolste** [comment]
Thanks! That fixed it (I updated future and pip-installed the master branch of biom-format via github url)

The last error: `ImportError: No module named api_proxy`
```
> qiita pet webserver start

/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/IPython/parallel/client/client.py:446: RuntimeWarning:
            Controller appears to be listening on localhost, but not on this machine.
            If this is true, you should specify Client(...,sshserver='you@192.168.1.110')
            or instruct your controller to listen on an external IP.
  RuntimeWarning)
Building documentation ...
Documentation successfully built
Traceback (most recent call last):
  File "/Users/hannes/miniconda2/envs/qiita/bin/qiita", line 430, in <module>
    qiita()
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/hannes/miniconda2/envs/qiita/bin/qiita", line 399, in start
    from qiita_pet.webserver import Application
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/qiita_pet/webserver.py", line 24, in <module>
    from qiita_pet.handlers.study_handlers import (
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/qiita_pet/handlers/study_handlers/__init__.py", line 16, in <module>
    from .base import (StudyIndexHandler, StudyBaseInfoAJAX, StudyDeleteAjax,
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/qiita_pet/handlers/study_handlers/base.py", line 14, in <module>
    from qiita_pet.handlers.api_proxy import (
ImportError: No module named api_proxy
(qiita)
```

I have the latest qiita master branch.
qiita's api_proxy package appears to have an __init__.py so I don't know why the import is not being resolved correctly.

```
ls qiita_pet/handlers/api_proxy
__init__.py        ontology.py        processing.py      studies.py         util.py
artifact.py        prep_template.py   sample_template.py tests
```

**Comment by josenavas** [comment]
If you are installing it using `pip install .` or `pip install -e .` the issue is that it is not defined in our setup.py, and hence not installed. In most of our installations we haven't detected this earlier because we usually change our pythonpath in our environments to point to the folder where we have qiita installed.

**Comment by HannesHolste** [comment]
Thanks @josenavas – fixed in PR #1850

It's almost working, but now having installed future v0.15.2, moi seems to be complaining because it expects exactly v0.13.0:

from [setup.py](https://github.com/biocore/mustached-octo-ironman/blob/master/setup.py) in moi master branch:
```
      install_requires=['future==0.13.0', 'tornado==3.1.1', 'toredis', 'redis',
                        'ipython[all]', 'click >= 3.3',
                        'python-dateutil==2.2'],
```

I noticed moi hasn' t been updated in over a year. Do you suggest removing that version constraint of 'future' in the moi repository, and testing if moi still builds...? (I don't have access)


full stack-trace:
```
> qiita pet webserver --no-build-docs start
Traceback (most recent call last):
  File "/Users/hannes/miniconda2/envs/qiita/bin/qiita", line 4, in <module>
    __import__('pkg_resources').require('qiita-spots==0.2.0.dev0')
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/setuptools-21.2.1-py2.7.egg/pkg_resources/__init__.py", line 2927, in <module>
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/setuptools-21.2.1-py2.7.egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/setuptools-21.2.1-py2.7.egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/setuptools-21.2.1-py2.7.egg/pkg_resources/__init__.py", line 637, in _build_master
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/setuptools-21.2.1-py2.7.egg/pkg_resources/__init__.py", line 650, in _build_from_requirements
  File "/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages/setuptools-21.2.1-py2.7.egg/pkg_resources/__init__.py", line 834, in resolve
pkg_resources.ContextualVersionConflict: (future 0.15.2 (/Users/hannes/miniconda2/envs/qiita/lib/python2.7/site-packages), Requirement.parse('future==0.13.0'), set(['moi']))
```

**Comment by antgonza** [comment]
I think that will be the best, could you issue a PR agains moi changing future? Thanks!

**Comment by HannesHolste** [comment]
@antgonza: moi package deps updated: https://github.com/biocore/mustached-octo-ironman/pull/38

**Comment by HannesHolste** [comment]
Hooray, got QIITA to run with webserver and SSL after many hours!!

Currently re-writing the documentation and doing another fresh install to double-check my instructions.

**Comment by HannesHolste** [comment]
Waiting for someone to review and merge #1852. New docs include support and instructions for conda. Also added troubleshooting section for OS X and ubuntu with many of the errors I had to resolve.

I tested the instructions on my local OSX with a fresh miniconda install, as well as a totally clean installation of ubuntu (see PR comment for details).

**Comment by antgonza** [comment]
I have conflicted feelings about the VM based on our experience with the QIIME VM, let's discuss in the Qiita meeting.
