### ISSUE TITLE
There are cases in which the QIIME mapping file is not generated

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#1916]
@antgonza found this traceback multiple times in the logs:

```python
    HTTPRequest(protocol='https', host='qiita.ucsd.edu', method='GET', uri='/study/description/prep_template/?prep_id=1748&study_id=10512', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.8,es;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'X-Forwarded-For': '73.217.94.32', 'Connection': 'upgrade', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36', 'Host': 'qiita.ucsd.edu', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'https://qiita.ucsd.edu/study/description/10512', 'X-Real-Ip': '73.217.94.32', 'Cookie': 'jlinkauthserver=davis; jlinksessionidx=z5109caad5d96a7e441999e7a96f20c28; jlinkappx=/employeeMyTimeEntry/calendar-time-entry.htm; xjlinkloginMyTimeEntry.User=OK; __utma=57960238.431222674.1463057811.1463410241.1463675783.2; __utmc=57960238; __utmz=57960238.1463410241.1.1.utmcsr=a4.ucsd.edu|utmccn=(referral)|utmcmd=referral|utmcct=/tritON/profile/SAML2/Redirect/SSO; user="ImFudG9uaW9nQHVjc2QuZWR1Ig==|1463762818|947f73f203ee2fbc2df70561c09076fe0c5e7588"; _ga=GA1.2.431222674.1463057811'})
    Traceback (most recent call last):
      File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
        callback()
      File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
        self._when_complete(method(*self.path_args, **self.path_kwargs),
      File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 2297, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/qiita_main/qiita_pet/handlers/study_handlers/prep_template.py", line 58, in get
        res = prep_template_ajax_get_req(self.current_user.id, prep_id)
      File "/home/qiita/qiita_main/qiita_pet/handlers/api_proxy/prep_template.py", line 162, in prep_template_ajax_get_req
        download_qiime = download_qiime[0]
    IndexError: list index out of range
```

Original discussion [here](https://github.com/biocore/qiita/pull/1915/files/366319c86da16c509c5e37fe6393a0591c88c2b9#r76405167).

**Comment by antgonza** [comment]
I just checked all the logs and I couldn't find the error. Additionally, the lines that started that discussion have been removed. Thus, closing.
