### ISSUE TITLE
Removing individual samples from the analysis generates an error

### ISSUE THREAD

**Issue by josenavas** [biocore/qiita#2055]
Looking at the logs, this is the error being generated:

```
[E 170120 12:00:11 websocket:306] Uncaught exception in /analysis/selected/socket/
    Traceback (most recent call last):
      File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/websocket.py", line 303, in wrapper
        return callback(*args, **kwargs)
      File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 2297, in wrapper
        return method(self, *args, **kwargs)
      File "/home/qiita/qiita/qiita_core/util.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/home/qiita/qiita/qiita_pet/handlers/websocket_handlers.py", line 92, in on_message
        artifacts = [Artifact(_id) for _id in data['proc_data']]
      File "/home/qiita/qiita/qiita_db/base.py", line 194, in __init__
        raise qdb.exceptions.QiitaDBUnknownIDError(id_, self._table)
    QiitaDBUnknownIDError: The object with ID '1' does not exists in table 'artifact'
```

**Comment by antgonza** [comment]
Assigning to @josenavas as I _think_ this can be resolved when the analysis is moved to a plugin.

**Comment by adswafford** [comment]
Have we had any movement on this? This is a large bug for analysis, particularly because the only ways around it are to:
1) Create a new prep information file with each subset you want to look at, followed by reuploading and reprocessing all of the sequencing data. This is a waste of user time, cpu time, and data storage
2) Analyze your data outside of Qiita

When fixing this, it would be a nice feature if we could drop samples based on metadata categories if possible. 

Perhaps all of this is irrelevant if the analysis is going to become a plugin, but do we know when?

**Comment by antgonza** [comment]
this was solved during the transition out of moi ...
