### ISSUE TITLE
Connection error triggers stochastic build failures

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#2166]
In some situations the Travis build will fail with a rather obscure error (the full traceback is shown below):

```
Error: error with status PGRES_TUPLES_OK and no message from the libpq
```

After some googling @antgonza came across this [issue](https://github.com/psycopg/psycopg2/issues/281) in the psycopg2 tracker, which points to a connection problem and is not necessarily a problem with psycopg2 (as per the maintainer's description). We noticed that this error would always be raised by [this function](https://github.com/biocore/qiita/blob/master/qiita_core/testing.py#L51).

```python
def wait_for_processing_job(job_id):
    """Waits until a processing job is completed
 
    Parameters
    ----------
    job_id : str
        Job id
    """
    job = ProcessingJob(job_id)
    while job.status not in ('success', 'error'):
       sleep(0.05)
    sleep(0.5)
```

We speculate that the reason why the connection fails is because of the `sleep` intervals, and if that's the case we would need to find a different way to wait for the status change.

--------------------------------

```
======================================================================
ERROR: test_post_artifact (qiita_pet.handlers.study_handlers.tests.test_artifact.NewArtifactHandlerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biocore/qiita/qiita_pet/handlers/study_handlers/tests/test_artifact.py", line 130, in test_post_artifact
    wait_for_prep_information_job(self.prep.id)
  File "/home/travis/build/biocore/qiita/qiita_core/testing.py", line 42, in wait_for_prep_information_job
    wait_for_processing_job(job_id)
  File "/home/travis/build/biocore/qiita/qiita_core/testing.py", line 60, in wait_for_processing_job
    while job.status not in ('success', 'error'):
  File "/home/travis/build/biocore/qiita/qiita_db/processing_job.py", line 286, in status
    return qdb.sql_connection.TRN.execute_fetchlast()
  File "/home/travis/build/biocore/qiita/qiita_db/sql_connection.py", line 510, in wrapper
    return func(self, *args, **kwargs)
  File "/home/travis/build/biocore/qiita/qiita_db/sql_connection.py", line 782, in execute_fetchlast
    return self.execute()[-1][0][0]
  File "/home/travis/build/biocore/qiita/qiita_db/sql_connection.py", line 510, in wrapper
    return func(self, *args, **kwargs)
  File "/home/travis/build/biocore/qiita/qiita_db/sql_connection.py", line 759, in execute
    return self._execute()
  File "/home/travis/build/biocore/qiita/qiita_db/sql_connection.py", line 706, in _execute
    self._raise_execution_error(sql, sql_args, e)
  File "/home/travis/build/biocore/qiita/qiita_db/sql_connection.py", line 651, in _raise_execution_error
    % (sql, str(sql_args), str(error)))
ValueError: Error running SQL query:
Query: SELECT processing_job_status
                     FROM qiita.processing_job_status
                        JOIN qiita.processing_job
                            USING (processing_job_status_id)
                     WHERE processing_job_id = %s
Arguments: [u'33b9adf9-691d-4902-af75-46545324176f']
Error: error with status PGRES_TUPLES_OK and no message from the libpq
```

**Comment by antgonza** [comment]
After more poking we realize that raising the sleeps fixed the issues and we haven't seen this problem in the latest PRs. My guess is that one of the tests was reseting the DB while another was trying to access it. I'm gonna close for now but let's reopen if this reappears.
