### ISSUE TITLE
QIIME2 reserved identifier column names should be validated

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#2799]
Currently, you can upload a sample or preparation information file that includes reserved QIIME2 column names ('feature id', 'feature-id', 'featureid', 'id', 'sample id', 'sample-id', 'sampleid'). The upload will work fine and the data will process fine, however when you create a meta-analysis and the data is loaded into a  QIIME2 `Metadata` object you will get this error:

```
1 validator jobs failed: Validator 91e01f77-2f05-4795-9fbb-2e28472d0267 error message: Error executing Validate: ['Traceback (most recent call last):
', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/qiita_client/plugin.py", line 255, in __call__
qclient, job_id, job_info[\'parameters\'], output_dir)
', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/qiita_client/plugin.py", line 100, in __call__
return self.function(qclient, server_url, job_id, output_dir)
', ' File "/home/qiita/qiita_spots/qtp-biom/qtp_biom/validate.py", line 163, in validate
new_biom_fp, md, join(out_dir), is_analysis, tree)
', ' File "/home/qiita/qiita_spots/qtp-biom/qtp_biom/summary.py", line 39, in _generate_html_summary
metadata = qiime2.Metadata.load(path)
', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/qiime2/metadata/metadata.py", line 315, in load
column_types=column_types)
', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/qiime2/metadata/io.py", line 68, in read
header = self._read_header()
', ' File "/home/qiita/miniconda3/envs/qiime2-2018.11/lib/python3.5/site-packages/qiime2/metadata/io.py", line 175, in _read_header
"\
\
%s" % (column_name, FORMATTED_ID_HEADERS))
', "qiime2.metadata.io.MetadataFileError: Metadata column name 'id' conflicts with a name reserved for the ID column header. Reserved ID column headers:

Case-insensitive: 'feature id', 'feature-id', 'featureid', 'id', 'sample id', 'sample-id', 'sampleid'

Case-sensitive: '#OTU ID', '#OTUID', '#Sample ID', '#SampleID', 'sample_name'

There may be more errors present in the metadata file. To get a full report, sample/feature metadata files can be validated with Keemei: https://keemei.qiime2.org

Find details on QIIME 2 metadata requirements here: https://docs.qiime2.org/2018.11/tutorials/metadata/
"]
```

Removing the offending column (in this case `id`) solves the problem.

**Comment by charles-cowart** [comment]
I'm thinking this could simply extend the checks we perform for PostgreSQL-reserved words. However, would it be suitable to restrict all sample information and prep information files, even if they will never use QIIME2? I believe so, but asking for feedback from @ElDeveloper and @antgonza

**Comment by ElDeveloper** [comment]
That should be fine, so as long as the error is general and clear enough to debug this problem.

**Comment by antgonza** [comment]
Fixed in https://github.com/biocore/qiita/pull/2842
