### ISSUE TITLE
Tornado tests fail randomly

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#622]
Some of the tests that verify the handlers are working correctly will stochastically fail, see below for two examples that were independently generated from the same SHA-1 in #618:

```python
======================================================================
FAIL: test_post (qiita_pet.test.test_study_handlers.TestStudyDescriptionHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biocore/qiita/qiita_pet/test/test_study_handlers.py", line 36, in test_post
    response = self.post('/study/description/1', post_args)
  File "/home/travis/build/biocore/qiita/qiita_pet/test/tornado_test_base.py", line 69, in post
    return self._fetch(url, 'POST', data, headers)
  File "/home/travis/build/biocore/qiita/qiita_pet/test/tornado_test_base.py", line 74, in _fetch
    return self.wait()
  File "/home/travis/anaconda/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 269, in wait
    self.__rethrow()
  File "/home/travis/anaconda/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 205, in __rethrow
    raise_exc_info(failure)
  File "/home/travis/anaconda/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 253, in timeout_func
    timeout)
AssertionError: Async operation timed out after 5 seconds
-------------------- >> begin captured logging << --------------------
tornado.general: WARNING: tornado.autoreload started more than once in the same process
tornado.access: INFO: 200 POST /study/description/1 (127.0.0.1) 6239.70ms
--------------------- >> end captured logging << ---------------------
```

```python
======================================================================
FAIL: test_get_exists (qiita_pet.test.test_study_handlers.TestMetadataSummaryHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biocore/qiita/qiita_pet/test/test_study_handlers.py", line 113, in test_get_exists
    'study_id': 1})
  File "/home/travis/build/biocore/qiita/qiita_pet/test/tornado_test_base.py", line 63, in get
    return self._fetch(url, 'GET', headers=headers)
  File "/home/travis/build/biocore/qiita/qiita_pet/test/tornado_test_base.py", line 74, in _fetch
    return self.wait()
  File "/home/travis/anaconda/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 269, in wait
    self.__rethrow()
  File "/home/travis/anaconda/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 205, in __rethrow
    raise_exc_info(failure)
  File "/home/travis/anaconda/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 253, in timeout_func
    timeout)
AssertionError: Async operation timed out after 5 seconds
-------------------- >> begin captured logging << --------------------
tornado.general: WARNING: tornado.autoreload started more than once in the same process
tornado.access: INFO: 200 GET /metadata_summary/?sample_template=1&study_id=1&prep_template=1 (127.0.0.1) 4980.13ms
--------------------- >> end captured logging << ---------------------
```

In #618, @squirrelo said:

> I've had it happen intermittently, my best guess is all tests are running on the same IOloop so it times out if too many are runnning at once or run in succession.

**Comment by squirrelo** [comment]
This was solved as a travis issue. Has not been seen in a week, so closing.
