### ISSUE TITLE
qiita webserver start should error nicely when the cluster hasn't been started

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/qiita#693]
When running `qiita webserver start` and the IPython cluster hasn't been started a traceback is shown on screen. The desired behavior is to have a message indicating what's wrong.

**Comment by antgonza** [comment]
Should this be here or in moi? 

cc @wasade

**Comment by wasade** [comment]
Likely moi

**Comment by antgonza** [comment]
I think it should be in both places so qiita has nice errors not based on imports.

**Comment by wasade** [comment]
I still think just moi for the sake of separation of concerns. qiita can catch an exception by moi, but I do not see a need for qiita to have direct interaction with compute subsystem.

**Comment by antgonza** [comment]
Currently, if the ipcluster is down, it will fail like:
```bash
$ qiita pet webserver --no-build-docs start --port 5558
Unable to connect to ipcluster(s): qiita-test-local
Traceback (most recent call last):
  File "/home/qiita_test/qiita_main/scripts/qiita", line 31, in <module>
    from qiita_ware.context import system_call, ComputeError
  File "/home/qiita_test/qiita_main/qiita_ware/context.py", line 274, in <module>
    context = Dispatch()
  File "/home/qiita_test/qiita_main/qiita_ware/context.py", line 62, in __init__
    self.demo = Client(profile=ctx_default)
  File "/home/qiita_test/.virtualenvs/qiita_t/lib/python2.7/site-packages/IPython/parallel/client/client.py", line 411, in __init__
    with open(url_file) as f:
IOError: [Errno 2] No such file or directory: u'/home/qiita_test/.ipython/profile_qiita-test-local/security/ipcontroller-client.json'
```
which I think has all the info required to know what's going on. 

BTW, if the cluster doesn't have more than 2 workers we get:
```
Traceback (most recent call last):
  File "/home/qiita_test/qiita_main/scripts/qiita", line 31, in <module>
    from qiita_ware.context import system_call, ComputeError
  File "/home/qiita_test/qiita_main/qiita_ware/context.py", line 274, in <module>
    context = Dispatch()
  File "/home/qiita_test/qiita_main/qiita_ware/context.py", line 69, in __init__
    'but you have %d' % workers)
ValueError: You need to have at least 2 IPython workers but you have 0
```

Thus, closing. If you want to improve this behavior please reopen and add what else will be needed. Thanks.
