### ISSUE TITLE
Adding a prep template results in an exception

### ISSUE THREAD

**Issue by wasade** [biocore/qiita#737]
I clicked "Add prep template" without having one selected and got the following

```python
Traceback (most recent call last):
  File "/Users/mcdonadt/.virtualenvs/python27/lib/python2.7/site-packages/tornado/web.py", line 1144, in _when_complete
    if result.result() is not None:
  File "/Users/mcdonadt/.virtualenvs/python27/lib/python2.7/site-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "/Users/mcdonadt/.virtualenvs/python27/lib/python2.7/site-packages/tornado/gen.py", line 221, in wrapper
    runner.run()
  File "/Users/mcdonadt/.virtualenvs/python27/lib/python2.7/site-packages/tornado/gen.py", line 505, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mcdonadt/ResearchWork/software/qiita/qiita_pet/handlers/study_handlers/description_handlers.py", line 591, in post
    study, user)
  File "/Users/mcdonadt/.virtualenvs/python27/lib/python2.7/site-packages/tornado/gen.py", line 533, in run
    self.yield_point.start(self)
  File "/Users/mcdonadt/.virtualenvs/python27/lib/python2.7/site-packages/tornado/gen.py", line 371, in start
    self.func(*self.args, **self.kwargs)
  File "/Users/mcdonadt/ResearchWork/software/qiita/qiita_pet/handlers/study_handlers/description_handlers.py", line 293, in add_prep_template
    callback((msg, msg_level, 'raw_data_tab', raw_data_id, pt_id))
```

**Comment by antgonza** [comment]
This error doesn't happen any more. Now if you click `Add prep template` without selecting a file you get:
```
An error occurred parsing the prep template: 
No columns to parse from file
```
Perhaps a nicer solution will be to simply do not show buttons when there are no data: Related to https://github.com/biocore/qiita/issues/903

**Comment by ElDeveloper** [comment]
Closing in favor of #903
