### ISSUE TITLE
Error while editing a study

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#816]
ERROR:
'environmental_packages'
TRACE:
Traceback (most recent call last):

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1141, in _when_complete
callback()

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 1162, in _execute_method
self._when_complete(method(*self.path_args, **self.path_kwargs),

File "/home/qiita/.virtualenvs/qiita/lib/python2.7/site-packages/tornado/web.py", line 2297, in wrapper
return method(self, *args, **kwargs)

File "/home/qiita/qiita_main/qiita_pet/handlers/study_handlers/edit_handlers.py", line 270, in post
'environmental_packages']

KeyError: 'environmental_packages'

**Comment by antgonza** [comment]
Note that the study gets updated but we get that error.
