### ISSUE TITLE
error in meta-analysis

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#830]
If you create a meta-analysis you get the error below, when looking at the wait page. Note that the jobs are created and run fine but there is no wait page. 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 341, in wrapper
    callback(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/httpserver.py", line 327, in _on_headers
    self.request_callback(self._request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/web.py", line 1567, in __call__
    handler = spec.handler_class(self, request, **spec.kwargs)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/websocket.py", line 23, in __init__
    self.group = Group(self.get_current_user(), forwarder=self.forward)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 50, in __init__
    for node in self._traverse(self.group):
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 60, in _traverse
    details = self._decode(r_client.get(current_id))
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 81, in _decode
    raise ValueError("Unable to decode data!")
ValueError: Unable to decode data!
ERROR:tornado.application:Exception in callback <functools.partial object at 0x10b8478e8>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 458, in _run_callback
    callback()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 341, in wrapper
    callback(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 331, in wrapped
    raise_exc_info(exc)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/httpserver.py", line 327, in _on_headers
    self.request_callback(self._request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/web.py", line 1567, in __call__
    handler = spec.handler_class(self, request, **spec.kwargs)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/websocket.py", line 23, in __init__
    self.group = Group(self.get_current_user(), forwarder=self.forward)
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 50, in __init__
    for node in self._traverse(self.group):
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 60, in _traverse
    details = self._decode(r_client.get(current_id))
  File "/Users/antoniog/.virtualenvs/qiita/lib/python2.7/site-packages/moi/group.py", line 81, in _decode
    raise ValueError("Unable to decode data!")
ValueError: Unable to decode data!
```

**Comment by antgonza** [comment]
After further investigation it seems like the error is due to having None in self.group with in redis/moi. A quick solution is to flush all keys in redis. I do not want to do this on qiita.colorado until I'm sure about what are the other implications of that, @josenavas, @wasade and/or @squirrelo, any ideas? BTW I do not know how a self.group could be None, perhaps it was left from previous tests but not sure, ideas will be appreciated.

**Comment by wasade** [comment]
That means the username is not being passed in. Username should be the
group (at the top level) or a group id (for a workflow). Submission of a
workflow will first go via a top level group, which is the username

AFAIK, we are not yet actually taking advantage of job history, so flushing
would only impact running jobs. I do not believe flushing will fix this.

**Comment by antgonza** [comment]
Thanks for the quick reply.

I was able to reproduce the error in my laptop and after further
investigation I got to the conclusion that flushing might solve it,
and it did. I'm currently running jobs locally without an issue. I'm
going to flush keys at qiita.colorado cause even if there are running
jobs, they are not tracking status due to that None.

Now, perhaps the issue is that both locally and in the server we
created testing keys in redis that do not have a username. What do you
think?

**Comment by antgonza** [comment]
After flushing qiita.colorado is working fine again.

**Comment by wasade** [comment]
What keys are shown in the user id hkey in redis?

None is valid. That flushing "worked" is concerning. Are jobs actually
being associated to users?

**Comment by wasade** [comment]
None is used for jobs that are not associated to a user btw

**Comment by wasade** [comment]
Is self.current_user being passed as group anywhere? The recent PR, if it
did not modify what was being passed, would likely result in unexpected
behavior

**Comment by squirrelo** [comment]
Everything that was passing self.current_user is now passing self.current_user.id, so it should still be working off of the user email as a string. Functionally, all the compute should still be getting the exact same information in the same format when starting work.

**Comment by wasade** [comment]
Job hierarchy appears to sane on qiita.microbio.me. That flushing made this
work is very concerning as we're addressing symptoms, not the problem which
is still undetermined.

On Mon, Feb 9, 2015 at 8:28 AM, Joshua Shorenstein <notifications@github.com

**Comment by squirrelo** [comment]
Can we close this?

**Comment by ElDeveloper** [comment]
I don't think so ...

**Comment by antgonza** [comment]
Nop. If we have another service using redis with qiita, qiita will
brake if messages are not in the desired format, which is a bug and
should be solved.

**Comment by wasade** [comment]
what about setting a different redis db?

**Comment by antgonza** [comment]
That will work. We could add a note in the install instructions saying
that qiita should have a dedicated db and then close this issue, what
do you guys think?

**Comment by squirrelo** [comment]
I'd also change this line in the qiita_config to a non-default number:
```
# The ID of the redis database
DB = 0
```

**Comment by antgonza** [comment]
Good idea, could you make those changes so we can close this?
