### ISSUE TITLE
fall back to default Qiita config

### ISSUE THREAD

**Issue by jairideout** [biocore/qiita#912]
From a fresh Qiita install, I get the following error:

```
$ qiita_env --help
Traceback (most recent call last):
  File "/Users/jairideout/.virtualenvs/qiita/bin/qiita_env", line 10, in <module>
    execfile(__file__)
  File "/Users/jairideout/dev/qiita/scripts/qiita_env", line 15, in <module>
    from qiita_db.environment_manager import (
  File "/Users/jairideout/dev/qiita/qiita_db/environment_manager.py", line 9, in <module>
    from qiita_db.ontology import Ontology
  File "/Users/jairideout/dev/qiita/qiita_db/ontology.py", line 29, in <module>
    from .base import QiitaObject
  File "/Users/jairideout/dev/qiita/qiita_db/base.py", line 30, in <module>
    from .sql_connection import SQLConnectionHandler
  File "/Users/jairideout/dev/qiita/qiita_db/sql_connection.py", line 90, in <module>
    from qiita_core.qiita_settings import qiita_config
  File "/Users/jairideout/dev/qiita/qiita_core/qiita_settings.py", line 14, in <module>
    qiita_config = ConfigurationManager()
  File "/Users/jairideout/dev/qiita/qiita_core/configuration_manager.py", line 121, in __init__
    with open(conf_fp, 'U') as conf_file:
IOError: [Errno 2] No such file or directory: '/Users/jairideout/dev/qiita/qiita_config.txt'
```

It looks like `QIITA_CONFIG_FP` is required to exist. It'd be helpful to have Qiita fall back to a default configuration, e.g., similar to how QIIME works.

**Comment by wasade** [comment]
I'm unable to recreate this issue. It looks like this does already [default](https://github.com/biocore/qiita/blob/master/qiita_core/configuration_manager.py#L117). @jairideout, can you please verify when you have a chance? 

```bash
(python27)18:00:10 scripts@issue_912$ unset QIITA_CONFIG_FP
(python27)18:00:29 scripts@issue_912$ ./qiita_env --help
Usage: qiita_env [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  clean_test     Cleans the test database environment.
  drop           Drops the database specified in config
  job_details    Pretty print moi job details
  make           Creates the database specified in config
  patch          Patches the database schema based on the...
  start_cluster  Start a compute environment
  stop_cluster   Stop a compute environment
  test           Test the environment Check to make sure that...

(python27)18:00:38 scripts@issue_912$ set | grep QIITA_CONFIG_FP
(python27)18:00:47 scripts@issue_912$
```

**Comment by jairideout** [comment]
Sorry about that! I thought `QIITA_CONFIG_FP` was required to be set to something.
