### ISSUE TITLE
Installation ubuntu 14.04

### ISSUE THREAD

**Issue by Jorge-C** [biocore/qiita#916]
I had some issues tryint to start up qiita 
```
Traceback (most recent call last):
  File "/home/jorge/anaconda/envs/qiita/bin/qiita_env", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/jorge/code/qiita/scripts/qiita_env", line 154, in <module>
    env()
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 384, in __call__
    return self.main(*args, **kwargs)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 370, in main
    self.invoke(ctx)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 614, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 623, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 524, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 236, in invoke
    return callback(*args, **kwargs)
  File "/home/jorge/code/qiita/scripts/qiita_env", line 71, in make
    make_environment(load_ontologies, download_reference, add_demo_user)
  File "/home/jorge/code/qiita/qiita_db/environment_manager.py", line 180, in make_environment
    admin_conn = SQLConnectionHandler(admin='admin_without_database')
  File "/home/jorge/code/qiita/qiita_db/sql_connection.py", line 120, in __init__
    self._open_connection()
  File "/home/jorge/code/qiita/qiita_db/sql_connection.py", line 155, in _open_connection
    raise RuntimeError("Cannot connect to database: %s" % str(e))
RuntimeError: Cannot connect to database: fe_sendauth: no password supplied
```
and it was solved by setting a password:
```
$ psql postgres
ALTER USER postgres PASSWORD 'supersecurepassword';
\q
```
and updating the qiita_config.txt file accordingly.

**Comment by Jorge-C** [comment]
and maybe restarting the service: `sudo service postgresql restart`

**Comment by adamrp** [comment]
As a potential workaround for this (although I haven't verified, since we fixed the problem in the manner than @Jorge-C mentioned above), I think the pg_hba.conf file can be modified to change authentication type for local users to trust (rather than, e.g., md5)
