### ISSUE TITLE
Error: date/time field value out of range: "6/21/11"

### ISSUE THREAD

**Issue by Jorge-C** [biocore/qiita#924]
There are issues when loading studies and using a non-US locale. This happened loading studies using @antgonza's script, but it's probably an issue in normal usage too. The error points toward `datestyle` settings.

For the record, error message:
```
+ qiita db load_sample_template studies/1024/sample_template_1024.txt --study 1024
Traceback (most recent call last):
  File "/home/jorge/anaconda/envs/qiita/bin/qiita", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/jorge/code/qiita/scripts/qiita", line 387, in <module>
    qiita()
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 384, in __call__
    return self.main(*args, **kwargs)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 370, in main
    self.invoke(ctx)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 614, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 623, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 614, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 623, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 524, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/home/jorge/anaconda/envs/qiita/lib/python2.7/site-packages/click/core.py", line 236, in invoke
    return callback(*args, **kwargs)
  File "/home/jorge/code/qiita/scripts/qiita", line 195, in load_sample_template
    sample_temp = load_sample_template_from_cmd(fp, study)
  File "/home/jorge/code/qiita/qiita_db/commands.py", line 153, in load_sample_template_from_cmd
    return SampleTemplate.create(sample_temp, Study(study_id))
  File "/home/jorge/code/qiita/qiita_db/metadata_template.py", line 1370, in create
    conn_handler.execute_queue(queue_name)
  File "/home/jorge/code/qiita/qiita_db/sql_connection.py", line 300, in execute_queue
    self._rollback_raise_error(queue, sql, sql_args, e)
  File "/home/jorge/code/qiita/qiita_db/sql_connection.py", line 263, in _rollback_raise_error
    str(sql_args), e)))
qiita_db.exceptions.QiitaDBExecutionError: 
Error running SQL query in queue CREATE_SAMPLE_TEMPLATE_1024: INSERT INTO qiita.required_sample_info (study_id, sample_id, physical_location, has_physical_specimen, has_extracted_data, sample_type, required_sample_info_status_id, collection_timestamp, host_subject_id, description, latitude, longitude) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
ARGS: (1024, '1024.SH004.C1.RH.1.1.bulk.6.11.G1.L00', 'ANLSequenced', 'y', 'y', 'XXQIITAXX', 4, '6/21/11', 'HS5', 'Bulk_soil', 41.015, -72.52847)
Error: date/time field value out of range: "6/21/11"
LINE 1: ...1.L00', 'ANLSequenced', 'y', 'y', 'XXQIITAXX', 4, '6/21/11',...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
```
and my psql date format:
```
jorge@hplap:~$ psql postgres
psql (9.3.6)
Type "help" for help.

postgres=# show datestyle;
 DateStyle 
-----------
 ISO, DMY
(1 row)
```

**Comment by Jorge-C** [comment]
This can be solved by setting
```
export PGDATESTYLE="ISO, MDY"
```
but there must be a way to let postgresql take care of that, right? [This SO answer](http://stackoverflow.com/a/13247214/1191119)
> If you can, use to_char for date output, and to_timestamp for date input whenever you need to use any date formats that might be ambiguous, like D/M/Y. Use ISO dates the rest of the time.

**Comment by antgonza** [comment]
Closing as this has been superseded by [these lines](https://github.com/biocore/qiita/blob/master/qiita_db/metadata_template/base_metadata_template.py#L1446)
