### ISSUE TITLE
study description page timing out in tests

### ISSUE THREAD

**Issue by squirrelo** [biocore/qiita#950]
The study description page is taking a long time to render during tests, which is throwing a 5 second timeout error pretty regularly now.

```python
======================================================================
FAIL: test_post (qiita_pet.test.test_study_handlers.TestStudyDescriptionHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/biocore/qiita/qiita_pet/test/test_study_handlers.py", line 114, in test_post
    response = self.post('/study/description/1', post_args)
  File "/home/travis/build/biocore/qiita/qiita_pet/test/tornado_test_base.py", line 57, in post
    return self._fetch(url, 'POST', data, headers)
  File "/home/travis/build/biocore/qiita/qiita_pet/test/tornado_test_base.py", line 62, in _fetch
    return self.wait()
  File "/home/travis/miniconda3/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 269, in wait
    self.__rethrow()
  File "/home/travis/miniconda3/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 205, in __rethrow
    raise_exc_info(failure)
  File "/home/travis/miniconda3/envs/env_name/lib/python2.7/site-packages/tornado/testing.py", line 253, in timeout_func
    timeout)
AssertionError: Async operation timed out after 5 seconds
-------------------- >> begin captured logging << --------------------
tornado.access: INFO: 200 POST /study/description/1 (127.0.0.1) 5702.12ms
--------------------- >> end captured logging << ---------------------
```

**Comment by squirrelo** [comment]
This is failing for any test in TestStudyDescriptionHandler, get or post, randomly.

**Comment by antgonza** [comment]
This is still failing randomly.

**Comment by squirrelo** [comment]
Where? I've seen travis fail for other things, but not this issue any more.

**Comment by antgonza** [comment]
Got the "Broken" email from master several times last night and had to
restart those builds several times. Those errors have disappeared as
they are now passing.

**Comment by antgonza** [comment]
This hasn't happen in a long time, closing now.
